### self study over numpy

In [2]:
import numpy as np
a= np.zeros((10,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [3]:
print(a.T)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [5]:
a= np.arange(6).reshape((3,2))
print(a)

[[0 1]
 [2 3]
 [4 5]]


In [7]:
np.reshape(a, (2,3)) #can reshape like this also

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5])

#### The following examples show the use of structured data type. Here, the field name and the corresponding scalar data type is to be declared.

In [13]:
#creating data type structure
# first create structured data type
import numpy as np
dt = np.dtype([('age',np.int8)])
print(dt)

## now apply it to ndarray object

a = np.array([(10,),(20,),(30,)], dtype = dt)
print(a)

# now file name can be used to access content of age column


print ("age structure is :  ",a['age'])

[('age', 'i1')]
[(10,) (20,) (30,)]
age structure is :   [10 20 30]


#### The following examples define a structured data type called student with a string field 'name', an integer field 'age' and a float field 'marks'. This dtype is applied to ndarray object.

In [36]:
#first create structured data type
dt=np.dtype([('name','<S10'),('age',np.int8),('marks',np.float)])
print(dt)
student=np.array([("aman",28,56.8),('xyz',9,60)], dtype=dt)
print("The complete structure: ",student)
#seprate info can be accessed using sctipting 
print(student['name'])
print(student['age'])
print(student['marks'])

[('name', 'S10'), ('age', 'i1'), ('marks', '<f8')]
The complete structure:  [(b'aman', 28, 56.8) (b'xyz',  9, 60. )]
[b'aman' b'xyz']
[28  9]
[56.8 60. ]


## NumPy More Array Attributes

### 1.numpy.itemsize---will return each elements length in byte

In [46]:
a=np.array([[1,2,3],[4,5,6]], dtype=np.int16)
print(a)
a.itemsize   # will return 1 for int8, 2 for int16 etc,   default int32----means 4 byte

[[1 2 3]
 [4 5 6]]


2

#### 2. numpy.flags

In [8]:
import numpy as np
a=np.array([1,2,3,4])
print(a.flags)
#for flag description refer to page 12 tutorials point exatra course material
# C_CONTIGUOUS : True-------------------->
#   F_CONTIGUOUS : True------------------>
#   OWNDATA : True----------------------->
#   WRITEABLE : True---------------------->
#   ALIGNED : True----------------------->
#   WRITEBACKIFCOPY : False-------------->  


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


### numpy array creation

In [9]:

print("1.numpy.empty(shape, dtype = float, order = 'C')\n2.numpy.zeros(shape, dtype = float, order = 'C')\n3.numpy.ones(shape, dtype = float, order = 'C')");


1.numpy.empty(shape, dtype = float, order = 'C')
2.numpy.zeros(shape, dtype = float, order = 'C')
3.numpy.ones(shape, dtype = float, order = 'C')


### NumPy Array From Existing Data

In [10]:
print("1. numpy.asarray(a, dtype = None, order = None)")

1. numpy.asarray(a, dtype = None, order = None)


### numpy.frombuffer
This function interprets a buffer as onedimensional
array. Any object that exposes the
buffer interface is used as parameter to return an ndarray.

numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
The constructor takes the following parameters.
buffer-object that exposes the buffer
dtype-type of objects defaut is float
count=how much data -1 means all
offset- starting point

In [18]:
#example
import numpy as np
s = b'Hello World'
a = np.frombuffer(s, dtype = 'S1')
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [27]:
#2 numpy.fromiter(iterable, dtype, count = -1)
# obtain iterator object from list
import numpy as np
list = range(5)
it = iter(list)
# use iterator to create ndarray
x = np.fromiter(it, dtype = float)
print(x)
#example next
s="aman"
n=np.fromiter(iter(s), dtype='S1')
print(n)

[0. 1. 2. 3. 4.]
[b'a' b'm' b'a' b'n']


In [28]:
numpy.arange
numpy.arange(start, stop, step, dtype)

NameError: name 'numpy' is not defined

In [29]:
numpy.linspace
numpy.linspace(start, stop, num, endpoint, retstep, dtype)

NameError: name 'numpy' is not defined

In [ ]:
numpy.logspace
numpy.logspace(start, stop, num, endpoint, base, dtype)

### indexing and slicing
slice(start,stop,step)

In [31]:
#example 1: slicing
import numpy as np
a = np.arange(10)
s = slice(2,7,2)
print (a[s])

[2 4 6]


In [33]:
#example 2
a = np.arange(10)
b = a[2:7:2]
print(b)

[2 4 6]


In [34]:
#s[start:]  --means start to end of a ndarray
#s[start:end]------------in between end not included


In [36]:
#advanced indexing
#example
import numpy as np
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0,1,2], [0,1,0]]    # includes item of position (0,0)(1,1)(2,0) in the matrix
print (y)

[1 4 5]


In [42]:

#example 2
import numpy as np
x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
print ('Our array is:')
print( x)
print ('\n')
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]
print ('The corner elements of this array are:')
print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


The corner elements of this array are:
[[ 0  2]
 [ 9 11]]


In [43]:
#boolean array indexing refer document

In [46]:
#removing the NaN(Not a Number )using ~ operator
import numpy as np
a = np.array([np.nan, 1,2,np.nan,3,4,5])
print (a[~np.isnan(a)])

[1. 2. 3. 4. 5.]


In [47]:
#filtering out the complex
import numpy as np
a = np.array([1, 2+6j, 5, 3.5+5j])
print (a[np.iscomplex(a)])

[2. +6.j 3.5+5.j]


### NumPy Iterating Over Array

In [7]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')
print ('Modified array is:')
for x in np.nditer(a):
    print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [9]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = 2*x     #x[...] refers to all element of x
print ('Modified array is:')
print (a)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [12]:
# In the following example, onedimensional  arrays corresponding to each column is  traversed by the iterator.
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')
print ('Modified array is:')
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):  #order =f means column major order=c default and row major
    print (x, end=" ")


Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[ 0 20 40] [ 5 25 45] [10 30 50] [15 35 55] 

In [15]:
#broadcasting and iteration combination
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('First array is:')
print (a)
print ('\n')
print ('Second array is:')
b = np.array([1, 2, 3, 4], dtype = int)
print (b)
print ('\n')
print ('Modified array is:')
for x,y in np.nditer([a,b]):
    print ("%d:%d" % (x,y))

First array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Second array is:
[1 2 3 4]


Modified array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In [16]:
#in numpy.char class are useful in performing vectorized string operations.

### numpy mathematical functions

In [19]:
import numpy as np
a = np.array([0,30,45,60,90])
print ('Sine of different angles:')
# Convert to radians by multiplying with pi/180
print (np.sin(a*np.pi/180))
print ('\n')
print ('Cosine values for angles in array:')
print (np.cos(a*np.pi/180))
print ('\n')
print ('Tangent values for given angles:')
print (np.tan(a*np.pi/180))

Sine of different angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [22]:
#rounding functions
import numpy as np
a = np.array([1.0,5.55, 123, 0.567, 25.532])
print( 'Original array:')
print (a)
print ('\n')
print ('After rounding:')
print (np.around(a))
print (np.around(a, decimals = 1))
print (np.around(a, decimals = -1))

Original array:
[  1.      5.55  123.      0.567  25.532]


After rounding:
[  1.   6. 123.   1.  26.]
[  1.    5.6 123.    0.6  25.5]
[  0.  10. 120.   0.  30.]


In [28]:
#numpy mod /remainder
import numpy as np
a = np.array([10,20,30])
b = np.array([3,5,7])
print ('First array:')
print (a)
print ('\n')
print ('Second array:')
print( b)
print ('\n')
print ('Applying mod() function:')
print (np.mod(a,b))
print ('\n')
print ("'Applying remainder() function:'")
print (np.remainder(a,b))

First array:
[10 20 30]


Second array:
[3 5 7]


Applying mod() function:
[1 0 2]


'Applying remainder() function:'
[1 0 2]


In [29]:
#complex number math functions
numpy.real() − returns the real part of the complex data type argument.
numpy.imag() − returns the imaginary part of the complex data type
argument.
numpy.conj() − returns the complex conjugate, which is obtained by changing
the sign of the imaginary part.
numpy.angle() − returns the angle of the complex argument. The function has
degree parameter. If true, the angle in the degree is returned, otherwise the
angle is in radians.

SyntaxError: invalid character in identifier (<ipython-input-29-ee6b389c0b9b>, line 2)

### NumPy Statistical Functions

#### numpy.amin() and numpy.amax()

In [31]:
import numpy as np
a = np.array([[3,7,5],[8,4,3],[2,4,9]])
print ('Our array is:')
print (a)
print ('\n')
print ('Applying amin() function:')
print (np.amin(a,1))  #column major
print ('\n')
print ('Applying amin() function again:')
print (np.amin(a,0))   #row major
print ('\n')
print ('Applying amax() function:')
print (np.amax(a))   # biggest
print ('\n')
print ('Applying amax() functionagain:')
print (np.amax(a, axis = 0))   #row major max

Our array is:
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function:
[3 3 2]


Applying amin() function again:
[2 4 3]


Applying amax() function:
9


Applying amax() functionagain:
[8 7 9]


### There are other many more functions of the numpy are available reffer to   document by tutorials point

### assignment :Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [44]:
# Mannual Solution :1
import numpy as np
a=np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150], dtype=int);
L=len(a)
print("Array tolat element=",L,'\n')
window_size=3
print("Given Window size=",window_size,'\n')
print("Hence, Toatal element in moving average array would be=",L-window_size+1)
print("hence we  need to run loop in range(L-window_size+1) i.e.:",L-window_size+1)   # the main logic n-k+1

outpu_inList=[]
for i in range(len(a)-window_size+1):
    outpu_inList.append(sum(a[i:i+window_size])/window_size)   #main logic sum(a[start:start+window_size]) till n-k+1
mov_avg_array=np.array(outpu_inList)
mov_avg_array

Array tolat element= 13 

Given Window size= 3 

Hence, Toatal element in moving average array would be= 11
hence we  need to run loop in range(L-window_size+1) i.e.: 11


array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [53]:
#solution 2 using function
def moving_average(a, w):  #a is 1-D array and w is window size
    out_list=[]
    length_a=len(a)
    total_moving_sum=length_a-w+1
    for i in range(total_moving_sum):
        out_list.append(sum(a[i:i+w])/w)
    out_result=np.array(out_list)
    return out_result
x=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size=3
moving_average(x,window_size)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

In [71]:
#using generator ---yield function
def moving_average1(a, w):  #a is 1-D array and w is window size
    
    length_a=len(a)
    total_moving_sum=length_a-w+1
    for i in range(total_moving_sum):
        yield sum(a[i:i+w])/w
    
x=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
window_size=3
#using above 
#1. using generator function  by list
m_v=list(moving_average1(x,window_size))
print("Moving average by yield through list:\n", m_v)

# 2. using generator function  by for loop
print("Moving average by yield through for loop")
for m in moving_average1(x,window_size):
    print(m)

Moving average by yield through list:
 [5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
Moving average by yield through for loop
5.0
4.666666666666667
5.666666666666667
6.666666666666667
9.666666666666666
28.666666666666668
49.333333333333336
72.66666666666667
84.0
93.33333333333333
116.33333333333333


In [72]:
#solution3 short cut
def mov_avg(x, w):
    for m in range(len(x)-(w-1)):
        yield sum(np.ones(w) * x[m:m+w]) / w    # np.ones to be disscuss
x=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
list(mov_avg(x, 3))

[5.0,
 4.666666666666667,
 5.666666666666667,
 6.666666666666667,
 9.666666666666666,
 28.666666666666668,
 49.333333333333336,
 72.66666666666667,
 84.0,
 93.33333333333333,
 116.33333333333333]